scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']

  - job_name: nvidia-gpu
    file_sd_configs:
      - files:
        - config/nvidia-gpu/*.json
        refresh_interval: 5m